version: '3.1'

services:
  db:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./db/db:/data/db
      - ./db/configdb:/data/configdb
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./web/files/proxy.conf:/etc/nginx/conf.d/proxy.conf
    depends_on:
      - app
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /opt/growi
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://db:27017/growi
    depends_on:
      - db
    command: npm start
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
    depends_on:
      - db
